### ISSUE TITLE
Deploying on charmed K8s

### ISSUE THREAD

**Issue by aym-frikha** [juju-solutions/bundle-istio#9]
Hello,

I'm trying to deploy istio bundle on a charmed cdk but had several issues.
Here are the steps I executed:
$ python3 scripts/cli.py ck setup --controller ckkf (from bundle-kubeflow)
$ juju-kubectl  label namespace default istio-injection=enabled
$ juju add-model istio-system ckkf
$ juju deploy cs:~kubeflow-charmers/bundle/istio --channel edge
$ juju-kubectl patch role -n istio-system istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'
$ juju-kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.5/samples/bookinfo/platform/kube/bookinfo.yaml
$ juju-kubectl  apply -f https://raw.githubusercontent.com/istio/istio/release-1.5/samples/bookinfo/networking/bookinfo-gateway.yaml

Those are the issue I had from Juju:
  https://pastebin.canonical.com/p/QSv4nxFrhz/

And those are the ones from istio-pilot-operator-0 pod:
https://pastebin.canonical.com/p/2RhjGgrwKD/

Is there something I did wrong ?

**Comment by ivanhitos** [comment]
same issue here.
